name: Claude Code

on:
  issue_comment:
    types: [created]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          allowed_bots: "claude[bot]"
          # Or use '*' to allow all bots:
          # allowed_bots: "*"